apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.app_deployment.name }}-hpa"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app_deployment.name }}
  minReplicas: {{ .Values.hpa.min_replica }}
  maxReplicas: {{ .Values.hpa.max_replica }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization:  {{ .Values.hpa.cpu_utilizatoion }} #  Average % of CPU utilization
