apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app_deployment.name }}-ingress"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bankapp.local # add 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.app_deployment.name }}-service"
            port:
              number: {{ default "8080" .Values.bankapp_svc.port}} 

