apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: {{ .Values.db_statefulset.name }}
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.db_statefulset.name }}
spec:
  serviceName: "{{ .Values.db_statefulset.name }}-headless"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db_statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db_statefulset.name }}
    spec:
      containers:
      - name: {{ .Values.db_statefulset.name }}
        image: {{ .Values.image.db }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:                      ### CRITICAL
              name: mysql-secret                  ### CRITICAL
              key: MYSQL_ROOT_PASSWORD    ### CRITICAL
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }} 
              key: MYSQL_DATABASE 
        volumeMounts:
        - name: "{{ .Values.db_statefulset.name }}-data"
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: "{{ .Values.db_statefulset.name }}-data"
      labels:
        app: {{ .Values.db_statefulset.name }}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage:  {{ .Values.db_statefulset.storage }}

