apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.db_statefulset.name }}-headless"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.db_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.db_statefulset.name }}
  ports:
  - protocol: TCP
    port: {{ default "3306" .Values.mysql_svc.port}}
    targetPort: {{ default "3306" .Values.mysql_svc.targetPort}}