apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.app_deployment.name }}-pvc"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.app_deployment.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.db_statefulset.storage }}
  storageClassName: manual

