apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.app_deployment.name }}-{{ default "bankapp-namespace" .Values.namespace }}-pv"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.app_deployment.name }}
spec:
  capacity:
    storage:  {{ .Values.db_statefulset.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/tmp/bankapp-mysql" # This will be stored on the host machine running KIND
