apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }} 
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.data.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.data.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
