apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_deployment.name }}-service"
  namespace: {{ default "bankapp-namespace" .Values.namespace }}
  labels:
    app: {{ .Values.app_deployment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app_deployment.name }}
  ports:
  - protocol: TCP
    port: {{ default "8080" .Values.bankapp_svc.port}} 
    targetPort: {{ default "8080" .Values.bankapp_svc.targetPort}} 
    nodePort: {{ default "30080" .Values.bankapp_svc.nodePort}}  # Exposes the app on this port of the host