# namespace 
namespace: bankapp-namespace

# name of configmap, database and db user.
configmap:  
  name: bankapp-config
  data:
      MYSQL_DATABASE: BankDB
      SPRING_DATASOURCE_USERNAME: root

## name, label and storage size for database 
db_statefulset:
  name: mysql
  storage: 5Gi

## name and label of app deployment
app_deployment: 
  name: bankapp
  cpu_req: 80m
  cpu_limit: 800m
  mem_req: 150Mi
  mem_limit: 700Mi

## image repository and tag of app and db.
image:
  app: trainwithshubham/springboot-bankapp:latest
  db: mysql:latest

# NodePort svc for bankapp
bankapp_svc:
    port: 8080
    targetPort: 8080
    nodePort: 30080 


# headless svc configuration for db
mysql_svc:
    port: 3306
    targetPort: 3306

# HPA minimun and maximum pods and average cpu utilization
hpa:
    min_replica: 1
    max_replica: 5
    cpu_utilizatoion: 40

# Secret for Database connectivity

secret:
  name: mysql-secret
  data: 
    MYSQL_ROOT_PASSWORD: Test@123       # (Base64 encoded 'Test@123')
    SPRING_DATASOURCE_PASSWORD: Test@123       # (Base64 encoded 'Test@123')
 
