name: My Workflow
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Clone the Code
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{secrets.DOCKER_PASSWORD }}
         logout: true
      - name: Build the App
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bank-app:v1 .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bank-app:v1
      - name: Deploy the APP
        run: |
          cd ${{ secrets.TARGET_DIRECTORY }}
          docker compose up -d
        
